src/mrsimulator/__main__.py
src/mrsimulator/web_ui/dimension.py
src/mrsimulator/web_ui/post_simulation.py

Added line broadening simulation feature and additional html formatting to slider bars

Mrsimulator max

---

setup.py

moved libraries outside windows if condition

Fixed setup.py for windows

---

CHANGELOG
src/mrsimulator/isotope_data.json
src/mrsimulator/spectrum.py
src/mrsimulator/tests/test_core.py
src/mrsimulator/tests/test_simulator.py

Expanded isotope dictionary to include more isotopes

Added isotope dictionary

---

docs/_static/style.css

This pull request applies style fixes from code review by [CodeFactor](https://www.codefactor.io).
---
For more information, click [here](https://www.codefactor.io/repository/github/deepanshs/mrsimulator/issues/master).

Apply fixes from CodeFactor

---

.github/workflows/continuous-integration-conda.yml
.github/workflows/continuous-integration-pip.yml
docs/requirements.rst
environment-dev.yml
requirements-dev.txt
setup.py

Add support for python v3.9

---

src/mrsimulator/method/__init__.py
src/mrsimulator/method/plot.py
src/mrsimulator/method/query.py
src/mrsimulator/method/tests/test_plot.py
src/mrsimulator/method/tests/test_query.py

Adds the event sequence diagram for each channel is a method.

Add sequence diagrams for multi-channel methods

---

docs/api_py/method/query.rst
docs/user_guide/method/method_advanced_user.rst
docs/user_guide/method/query_objects.rst
examples_source/1D_simulation(crystalline)/plot_9_custom_method_Hahnecho.py
src/c_lib/base/base_model.pyx
src/mrsimulator/method/__init__.py
src/mrsimulator/method/event.py
src/mrsimulator/method/plot.py
src/mrsimulator/method/query.py
src/mrsimulator/method/tests/test_event.py
src/mrsimulator/method/tests/test_method_utils.py
src/mrsimulator/method/tests/test_plot.py
src/mrsimulator/method/tests/test_query.py
src/mrsimulator/method/tests/test_summary.py
src/mrsimulator/method/tests/test_transitions.py
src/mrsimulator/method/utils.py
src/mrsimulator/methods/correlation.py

Name space change

---

pyproject.toml

Fix Building library from source errors out #137

---

.flake8
src/mrsimulator/__init__.py
src/mrsimulator/benchmark.py
src/mrsimulator/method/lib/base.py
src/mrsimulator/method/lib/ssb2d.py
src/mrsimulator/method/plot.py
src/mrsimulator/method/query.py
src/mrsimulator/method/tests/lib_tests/test_correlation.py
src/mrsimulator/method/tests/test_method_utils.py
src/mrsimulator/method/tests/test_plot.py
src/mrsimulator/method/utils.py
src/mrsimulator/methods.py
src/mrsimulator/signal_processing/__init__.py
src/mrsimulator/signal_processing/_base.py
src/mrsimulator/signal_processing/apodization.py
src/mrsimulator/signal_processing/baseline.py
src/mrsimulator/signal_processing/tests/test_apodization.py
src/mrsimulator/spin_system/isotope.py
src/mrsimulator/spin_system/tests/test_spin_sys_simplify.py
src/mrsimulator/transition/tests/test_transition_list.py
src/mrsimulator/utils/__init__.py
src/mrsimulator/utils/spectral_fitting.py
src/mrsimulator/utils/tests/test_parseable.py
src/mrsimulator/utils/tests/test_single_site_sys_gen.py
src/mrsimulator/utils/tests/test_spectral_fitting.py
tests/test_orientations_and_triangle_interpolation.py
tests/wigner/matrix/wigner_matrix_test.py

Code cleanup and spell checks.

Minor code cleanup

---

docs/api_py/methods/BlochDecayCTSpectrum.rst
docs/api_py/methods/BlochDecaySpectrum.rst
examples_source/1D_simulation(crystalline)/plot_1_PotassiumSulfate.py
examples_source/1D_simulation(crystalline)/plot_2_Coesite.py
examples_source/1D_simulation(crystalline)/plot_4_satellite_transition_sim.py
examples_source/1D_simulation(crystalline)/plot_5_multi-quantum_spectrum.py
examples_source/1D_simulation(crystalline)/plot_9_custom_method_Hahnecho.py
examples_source/2D_simulation(crystalline)/plot_0_MQMAS_RbNO3.py
examples_source/2D_simulation(crystalline)/plot_1_STMAS_RbNO3.py
examples_source/2D_simulation(crystalline)/plot_2_SAS_Rb2SO4.py
examples_source/2D_simulation(crystalline)/plot_4_DAS_Coesite.py
examples_source/2D_simulation(crystalline)/plot_5_COASTER_Rb2CrO4.py
examples_source/2D_simulation(crystalline)/plot_6_PASS_itraconazole_drug.py
examples_source/2D_simulation(crystalline)/plot_7_QSSB_Rb2SO4.py
examples_source/2D_simulation(crystalline)/plot_8_MAF.py
examples_source/2D_simulation(crystalline)/plot_9_shifting-d.py
fitting_source/2D_fitting/plot_4_NiCl2.2D2O_shifting-d.py
signal_processing_source/plot_2_exponential.py
signal_processing_source/plot_3_gaussian.py
signal_processing_source/plot_5_tophat.py
tests/2D_spectrum_tests/test_coaster.py

The PR fixes
- Coaster examples mixing event
- plot figure size for examples
- general spelling errors.
Adds
- test for coaster method

Fix mixing query event for COASTER example

---

src/mrsimulator/method/__init__.py
src/mrsimulator/method/lib/base.py
src/mrsimulator/method/tests/test_method.py
src/mrsimulator/method/tests/test_plot.py
src/mrsimulator/method/utils.py

Closes #194 and adds check preventing more than 2 spectral dimensions.

Method checks

---

src/mrsimulator/__init__.py

Update version number to 0.7.0

---

CITATION.cff
MANIFEST.in
README.md

Update readme.md and citation file.

Post-release updates

---

src/mrsimulator/signal_processor/apodization.py

fixed 0Hz bug in apodization

---

.readthedocs.yaml

Fix for the bug failing the RTD build

Update read the docs config

---

.gitignore
fitting_source/1D_fitting/plot_7_27Al_Extended_Czjzek.py
setup.py
src/c_lib/base/base_model.pxd
src/c_lib/base/base_model.pyx
src/c_lib/clib/clib.pxd
src/c_lib/clib/clib.pyx
src/c_lib/include/config.h
src/c_lib/include/histogram.h
src/c_lib/include/vm.h
src/c_lib/include/vm_linalg.h
src/c_lib/lib/frequency_averaging.c
src/c_lib/lib/histogram.c
src/c_lib/lib/interpolation.c
src/c_lib/lib/vm_linalg.c
src/mrsimulator/method/utils.py
src/mrsimulator/models/analytical_distributions.py
src/mrsimulator/models/czjzek.py
src/mrsimulator/models/tests/test_roots.py
src/mrsimulator/models/utils.py
tests/test_clib.py

Djs/Code Optimization

---

src/mrsimulator/signal_processor/apodization.py
src/mrsimulator/simulator/__init__.py
src/mrsimulator/transition/base.py
src/mrsimulator/transition/pathway.py
src/mrsimulator/utils/extra.py

- replace `np.Inf` with `np.inf`
- explicit conversion of array to list

Code change for Numpy 2.0 compatibility

---

.github/workflows/continuous-integration-pip.yml
docs/api_py/method/event.rst
docs/user_guide/method/method.rst
examples_source/1D_simulation(crystalline)/plot_9_custom_method_Hahnecho.py
examples_source/2D_simulation(crystalline)/plot_4_DAS_Coesite.py
examples_source/2D_simulation(crystalline)/plot_5_COASTER_Rb2CrO4.py
examples_source/2D_simulation(crystalline)/plot_8_MAF.py
examples_source/2D_simulation(crystalline)/plot_9_shifting-d.py
examples_source/2D_simulation(crystalline)/plot_9a_sideband_sideband_correlation.py
fitting_source/2D_fitting/plot_2_Coesite_DAS.py
fitting_source/2D_fitting/plot_4_NiCl2.2D2O_shifting-d.py
src/c_lib/base/base_model.pyx
src/mrsimulator/method/__init__.py
src/mrsimulator/method/event.py
src/mrsimulator/method/lib/base.py
src/mrsimulator/method/plot.py
src/mrsimulator/method/spectral_dimension.py
src/mrsimulator/method/tests/test_event.py
src/mrsimulator/method/tests/test_method_utils.py
src/mrsimulator/method/tests/test_transitions.py
src/mrsimulator/method/utils.py
tests/1D_spectrum_tests/test_coupling_freq_contrib.py
tests/2D_spectrum_tests/test_inadequate.py
tests/test_gamma_angles.py

- `RotationEvent` alias of `MixingEvent`
- All doc reference to `MixingEvent` are updated to `RotationEvent`
- Renamed `BaseEvent` -> `FreeEvent`

Add RotationEvent as an alias to MixingEvent

---

.github/workflows/continuous-integration-pip.yml
src/c_lib/lib/simulation.c

The issue was related to the recent update in openblas lib.
For release note:
- Fixed corner cases involving the handling of NAN and INFINITY arguments in ?SCAL on all architectures
https://github.com/OpenMathLib/OpenBLAS/pull/4829/files

Fix NaN issue on macOS

---

src/c_lib/base/base_model.pxd
src/c_lib/base/base_model.pyx
src/c_lib/include/object_struct.h
src/c_lib/lib/mrsimulator.c
src/c_lib/test/test.pxd
src/mrsimulator/simulator/__init__.py
src/mrsimulator/spin_system/isotope.py
src/mrsimulator/spin_system/tests/test_isotope.py
tests/2D_spectrum_tests/test_das.py
tests/2D_spectrum_tests/test_mqmas.py

code changed for setting default, but tests fail where the shifts are checked.

Default origin offset

---

docs/credits/license.rst
docs/index.rst
docs/installation/colab.rst
docs/installation/devs.rst
docs/installation/pip.rst
docs/installation/requirements.rst
docs/installation/source_install/linux.rst
docs/installation/source_install/macosx.rst
docs/installation/source_install/windows.rst
docs/installation/troubleshooting.rst
docs/installation/troubleshooting/colab.rst
docs/installation/troubleshooting/install_python.rst
docs/installation/troubleshooting/package_manager.rst
docs/installation/troubleshooting/python_errors.rst
docs/installation/users.rst
docs/introduction/fitting_example.rst
docs/introduction/getting_started.rst
docs/introduction/isotopomers_example.rst
docs/theory/models.rst
docs/user_guide/io/mrsim_IO.rst
docs/user_guide/method/echo_symm_classes.rst
docs/user_guide/method/method.rst
docs/user_guide/method/spin_trans_symm.rst
docs/user_guide/signal_processor/signal_processor.rst
docs/user_guide/simulator/simulator.rst
docs/user_guide/spin_system/spin_system.rst
docs/user_guide/spin_system_distributions/czjzek.rst
docs/user_guide/spin_system_distributions/extended_czjzek.rst
docs/user_guide/spin_system_distributions/single_site_sys_gen.rst

Docs grammar fixes

---

src/mrsimulator/utils/spectral_fitting.py

Fix the sign issue in custom czjzek and ext czjzek distribution fit.
**Bef
ore**
**After**

Bug fix in czjzek fit
